baseURL = "https://daniellaera.com/"
languageCode = "en-us"
title = "My Hugo Blog"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  author = "Your Name"
  defaultTheme = "auto"  # light/dark/auto
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10